/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.gltf --transform 
Files: car.gltf [11.77MB] > C:\Users\bayas\Downloads\pony_cartoon\car-transformed.glb [1.11MB] (91%)
Author: Slava Z. (https://sketchfab.com/slava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
Title: Pony Cartoon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Body_SG1} rotation={[-Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Ground_SG} rotation={[-Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Interior_SG} rotation={[-Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Windows_SG} rotation={[-Math.PI / 2, 0, 0]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
