/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 girl.gltf --transform 
Files: girl.gltf [5.94MB] > C:\Users\bayas\Downloads\rikuhachima_aru\girl-transformed.glb [482.86KB] (92%)
Author: Voon Hong Liang (https://sketchfab.com/vhongliang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rikuhachima-aru-59e88edc84d341e0a4173ce49b8c4904
Title: Rikuhachima Aru
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const { scene } = useGLTF('/girl-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_5.geometry} material={materials.body} skeleton={nodes.Object_5.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.body} skeleton={nodes.Object_6.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.body} skeleton={nodes.Object_7.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.material_0} skeleton={nodes.Object_8.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Hair} skeleton={nodes.Object_9.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Hair} skeleton={nodes.Object_10.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Hair} skeleton={nodes.Object_11.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Hair} skeleton={nodes.Object_12.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Hair} skeleton={nodes.Object_13.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.Hair} skeleton={nodes.Object_14.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Halo} skeleton={nodes.Object_15.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.material_0} skeleton={nodes.Object_16.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.material_0} skeleton={nodes.Object_17.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.material_0} skeleton={nodes.Object_18.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.material_0} skeleton={nodes.Object_19.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.material_0} skeleton={nodes.Object_20.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.material_0} skeleton={nodes.Object_21.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.material_0} skeleton={nodes.Object_22.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.material_0} skeleton={nodes.Object_23.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.material_0} skeleton={nodes.Object_24.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.material_0} skeleton={nodes.Object_25.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.face} skeleton={nodes.Object_26.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.brow_crease} skeleton={nodes.Object_27.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.face} skeleton={nodes.Object_28.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.face} skeleton={nodes.Object_29.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.face} skeleton={nodes.Object_30.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.brow_crease} skeleton={nodes.Object_31.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_32.geometry} material={materials.material_1} skeleton={nodes.Object_32.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.face} skeleton={nodes.Object_33.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_34.geometry} material={materials.brow_crease} skeleton={nodes.Object_34.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.brow_crease} skeleton={nodes.Object_35.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_36.geometry} material={materials.brow_crease} skeleton={nodes.Object_36.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.brow_crease} skeleton={nodes.Object_37.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_38.geometry} material={materials.mouth} skeleton={nodes.Object_38.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.brow_crease} skeleton={nodes.Object_39.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_40.geometry} material={materials.material_1} skeleton={nodes.Object_40.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_41.geometry} material={materials.brow_crease} skeleton={nodes.Object_41.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_42.geometry} material={materials.brow_crease} skeleton={nodes.Object_42.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_43.geometry} material={materials.material_1} skeleton={nodes.Object_43.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_44.geometry} material={materials.material_1} skeleton={nodes.Object_44.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_45.geometry} material={materials.cheek} skeleton={nodes.Object_45.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_46.geometry} material={materials.material_41} skeleton={nodes.Object_46.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_47.geometry} material={materials.material_42} skeleton={nodes.Object_47.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_48.geometry} material={materials.body} skeleton={nodes.Object_48.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/girl-transformed.glb')
