/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mac.gltf --transform 
Files: mac.gltf [94.71KB] > C:\Users\bayas\Downloads\apple_mac_mini_m1\mac-transformed.glb [49.28KB] (48%)
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-mac-mini-m1-79f1f864089d423fb06d220fe2085c71
Title: Apple Mac Mini M1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MacMini_MatteBlack_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MacMini_PowerButton_0.geometry} material={materials.PowerButton} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MacMini_Light_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
