/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shos.gltf --transform 
Files: shos.gltf [6.72MB] > C:\Users\bayas\Downloads\shos\shos-transformed.glb [684.37KB] (90%)
Author: Danny Escobar Castro (https://sketchfab.com/NOTTIME)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/test-shos-realitycapture-311cc9511f25496cbd7af392d14fd89f
Title: Test shos RealityCapture
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shos-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.default_tex0} />
    </group>
  )
}

useGLTF.preload('/shos-transformed.glb')
